export default {
 UPDATE_USER_PROFILE_START: "UPDATE_USER_PROFILE_START",

 UPDATE_USER_PROFILE_SUCCESS: "UPDATE_USER_PROFILE_SUCCESS",
 
 UPDATE_USER_PROFILE_FAILURE: "UPDATE_USER_PROFILE_FAILURE",

SET_UPDATE_INFO_LOADING: "SET_UPDATE_INFO_LOADING",

SET_UPDATE_INFO_ERRORS: "SET_UPDATE_INFO_ERRORS"
};
